# Generated by Django 2.1.3 on 2018-12-01 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('public', models.NullBooleanField(default=True)),
                ('max_num_people', models.IntegerField(default=10)),
                ('num_people', models.IntegerField(default=0)),
                ('tag1', models.CharField(blank=True, max_length=20, null=True)),
                ('tag2', models.CharField(blank=True, max_length=20, null=True)),
                ('tag3', models.CharField(blank=True, max_length=20, null=True)),
                ('tag4', models.CharField(blank=True, max_length=20, null=True)),
                ('tag5', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.TextField(null=True)),
                ('meeting', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2018, 12, 1))),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Tendency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=20, unique=True)),
                ('auth_pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Tendency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.SmallIntegerField(default=1)),
                ('learning', models.SmallIntegerField(default=1)),
                ('numberPeople', models.SmallIntegerField(default=1)),
                ('friendship', models.SmallIntegerField(default=1)),
                ('environment', models.SmallIntegerField(default=1)),
                ('style', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.User')),
            ],
        ),
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.User')),
            ],
        ),
        migrations.AddField(
            model_name='planner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.User'),
        ),
        migrations.AlterUniqueTogether(
            name='user_group',
            unique_together={('user', 'group')},
        ),
    ]
